# Generated by Django 5.0.3 on 2024-08-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
        migrations.RenameModel(
            old_name='Estudantes',
            new_name='Estudante',
        ),
    ]
