# Generated by Django 5.0.3 on 2024-08-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_curso_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nome',
        ),
    ]
