# Generated by Django 5.0.3 on 2024-08-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_matricula'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matricula',
            new_name='Matriculas',
        ),
    ]
